name: hikaru
version: 0.1.0.0
synopsis: Haskell web micro framework
category: Web
description: |
  Hikaru is a micro framework for web applications.
  It provides applicative routing, content negotiation
  and a customizable action monad.

  (It is also a Star Trek reference, which is apparently
  a requirement for this class of software.)

author: Jan Hamal Dvořák
github: mordae/hikaru
maintainer: mordae@anilinux.org

copyright: Jan Hamal Dvořák
license-file: LICENSE.md
license: AGPL-3

build-type: Simple
extra-source-files: README.md

ghc-options: -Wall -Wcompat
default-extensions:
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveGeneric
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies

dependencies:
  - aeson              >= 1.4  && <1.5
  - base               >= 4.12 && <4.13
  - base-prelude       >= 1.3  && <1.4
  - http-types         >= 0.12 && <0.13
  - lucid              >= 2.9  && <2.10
  - binary             >= 0.8  && <0.9
  - bytestring         >= 0.10 && <0.11
  - case-insensitive   >= 1.2  && <1.3
  - containers         >= 0.6  && <0.7
  - mtl                >= 2.2  && <2.3
  - resourcet          >= 1.2  && <1.3
  - string-conversions >= 0.4  && <0.5
  - text               >= 1.2  && <1.3
  - text-icu           >= 0.7  && <0.8
  - wai                >= 3.2  && <3.3
  - wai-extra          >= 3.0  && <3.1

library:
  source-dirs: lib
  dependencies: []

  exposed-modules:
    - Web.Hikaru
    - Web.Hikaru.Types
    - Web.Hikaru.Media
    - Web.Hikaru.Route
    - Web.Hikaru.Dispatch
    - Web.Hikaru.Action

# EOF
